### ISSUE TITLE
[QUESTION] Github token

### ISSUE THREAD

**Issue by kokonut27** [DillonB07/DillonB07#2]
Hiya, I just had a quick question with the GitHub token, because the metrics look pretty cool lol.

So what kind of scopes do I have to use for the token? Thanks!

**Comment by transcental** [comment]
> No additional scopes are needed for basic metrics, but you may have to grant additional scope depending on what features you're planning to use:

> public_repo scope for some plugins
read:org scope for all organizations related metrics
repo scope for all private repositories related metrics
read:user scope may also be required for some private repositories related metrics

> A scope-less token can still display private contributions by enabling Include private contributions on my profile in your account settings

> If a plugin has not enough scopes to operate (and plugins_errors_fatal isn't enabled), it'll be reported in the rendering

Personally, I gave it all of the read permissions.
For more info, check out the README: https://github.com/lowlighter/metrics#1-create-a-github-personal-token

**Comment by transcental** [comment]
I like your README with the stats embedded into the text. That's also a cool way of doing it.

**Comment by kokonut27** [comment]
Thanks! :D

**Comment by transcental** [comment]
Np
